# https://github.com/chabad360/hugo-gh-pages
name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Generate config.yaml
        run: python gen_config.py
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.JENKINS_PERSONAL_TOKEN }}
          branch: main
          repo: OpenMS/openms.github.io
          hugoVersion: extended_0.98.0
